apiVersion: v1
kind: Service
metadata:
  name: delightful-web-service
  namespace: delightful-services
spec:
  selector:
    app: delightful-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
